convocat2/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic.base import TemplateView
from django.contrib import admin
from django.conf import settings

urlpatterns = patterns('convocat2.views.inscripcion',

    url(r'^convocat2/inscripcion/iniciar-inscripcion$',      'iniciarInscripcion', name="iniciarInscripcion"),
    url(r'^convocat2/inscripcion/datos-personales$',      'datosPersonales', name="datosPersonales"),
    url(r'^convocat2/inscripcion/formacion-academica$',   'formacionAcademica', name="formacionAcademica"),
    url(r'^convocat2/inscripcion/formacion-academica/eliminar/(\d+)$', 'eliminarFormacionAcademica', name="eliminarFormacionAcademica"),

    url(r'^convocat2/inscripcion/formacion-tics$',        'formacionTics', name="formacionTics"),
    url(r'^convocat2/inscripcion/formacion-tics/eliminar/(\d+)$', 'eliminarFormacionTics', name="eliminarFormacionTics"),

    url(r'^convocat2/inscripcion/conocimientos$',         'conocimientosEspecificos', name="conocimientosEspecificos"),
    url(r'^convocat2/inscripcion/idiomas$',               'idiomasManejados', name="idiomasManejados"),
    url(r'^convocat2/inscripcion/idiomas/eliminar/(\d+)$', 'eliminarIdioma', name="eliminarIdioma"),

    url(r'^convocat2/inscripcion/experiencia-ensenanza$',             'experienciaEnsenanza', name="experienciaEnsenanza"),
    url(r'^convocat2/inscripcion/experiencia-ensenanza/eliminar/(\d+)$', 'eliminarExperienciaEnsenanza', name="eliminarExperienciaEnsenanza"),

    url(r'^convocat2/inscripcion/finalizar$',      'finalizar', name="finalizar"),
    url(r'^convocat2/inscripcion/finalizada$',      'finalizada', name="finalizada"),

    url(r'^convocat2/inscripcion/soportes$',      'soportes', name="soportes"),

)

urlpatterns += patterns('convocat2.views.dashboard',
    url(r'^convocat2/resultados$',      'dashboard', name="dashboard2"),
    url(r'^convocat2/resultadosME$',      'reporteME', name="reporteME2"),
    url(r'^convocat2/impresionME/(\d+)$',      'impresionME', name="impresionME2"),
    url(r'^convocat2/tablero_control/(\d*)$', 'tablero_control', name="tablero_control2"),
    url(r'^convocat2/tablero_control/actividades/(\d*)$', 'actividades', name="tableroControlActividades2"),
    url(r'^convocat2/tablero_control/guardarArchivos$', 'guardarArchivo', name="tableroControlGuardarArchivo2"),
    url(r'^convocat2/tablero_control/guardarEstadoDeAvance$', 'guardarEstadoDeAvance', name="tableroControlGuardarEstadoDeAvance2"),
    url(r'^convocat2/tablero_control/guardarGrupo/(\d*)$', 'guardarGrupo', name="tableroControlGuardarGrupo2"),
    url(r'^convocat2/tablero_control/guardarVariablesPorAula$', 'guardarVariablesPorAula', name="tableroControlGuardarVariablesPorAula2"),
    url(r'^convocat2/tablero_control/guardarVariablesPorSede$', 'guardarVariablesPorSede', name="tableroControlGuardarVariablesPorSede2"),
    url(r'^convocat2/tablero_control/eliminarGrupo/(\d*)$', 'eliminarGrupo', name="tableroControlEliminarGrupo2"),
    url(r'^convocat2/tablero_control/eliminarArchivo/(\d*)$', 'eliminarArchivo', name="tableroControlEliminarArchivo2"),
    url(r'^convocat2/obtenerGruposPorConceptoActividad/(\d*)$', 'obtenerGruposPorConceptoActividad', name="tableroControlObtenerGruposPorConceptoActividad2"),
)

tita/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic.base import TemplateView
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

admin.autodiscover()


urlpatterns = static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) # solo en servidor de desarrollo


urlpatterns += patterns('',
    url(r'^select2/', include('django_select2.urls')),

    url(r'^logged_user$', 'campus.views.logged_user', name="logged_user"),

    url(r'^login/$', 'django.contrib.auth.views.login', {'template_name':'login.html'}, name='login'),
    url(r'^logout/$', 'django.contrib.auth.views.logout', {'next_page':'home'}, name='logout'),
    url(r'^cambiar-pass/$', 'django.contrib.auth.views.password_change', {'template_name':'cambiar-pass.html', 'post_change_redirect':'home'}, name='cambiar_pass'),

    url(r'^admin/', include(admin.site.urls)),

    #url(r'^$', TemplateView.as_view(template_name='info/index.html'), name='home'),
    url(r'^$', TemplateView.as_view(template_name='index.html'), name='home'),
    url(r'^antecedentes/$', TemplateView.as_view(template_name='info/antecedentes.html'), name="info_antecedentes"),
    url(r'^infogeneral/$', TemplateView.as_view(template_name='info/infogeneral.html'), name="info_general"),
    url(r'^calendario/$', TemplateView.as_view(template_name='info/calendario.html'), name="info_calendario"),
    url(r'^requisitos/$',TemplateView.as_view(template_name='info/requisitos.html'), name="info_requisitos"),
    url(r'^registrarse/$',TemplateView.as_view(template_name='info/registrarse.html'), name="info_registrarse"),
    url(r'^contactenos/$',TemplateView.as_view(template_name='info/contactenos.html'), name="info_contactenos"),
    #url(r'^tablero_control/$',TemplateView.as_view(template_name='dashboard/tablero_control.html'), name="tablero_control"),


    url('', include('convocat.urls')),
    url('', include('convocat2.urls')),
    url('', include('estudiante.urls')),
    url(r'^encuestas/', include('survey.urls')),
    url(r'^campus/', include('campus.urls')),
    url('', include('cronograma.urls')),
    url('', include('malla.urls')),
    url('', include('bilinguismo.urls')),
)

convocat2/models.py
# encoding:utf-8
import random, string, os, datetime
from django.db import models
from django.contrib.auth.models import User
from estudiante.models import SEDES
from dateutil.relativedelta import relativedelta
from datetime import date

class Departamento(models.Model):
    nombre = models.CharField( max_length=255, verbose_name='nombre')
    codigo = models.CharField( max_length=10, null=True, verbose_name='código')
    latitud = models.FloatField(null=True)
    longitud = models.FloatField(null=True)

    def __unicode__(self):
        return self.nombre


class Municipio(models.Model):
    nombre = models.CharField( max_length=255, verbose_name='nombre')
    departamento = models.ForeignKey(Departamento, verbose_name='departamento')
    codigo = models.CharField( max_length=10, null=True, verbose_name='código')
    latitud = models.FloatField(null=True)
    longitud = models.FloatField(null=True)

    def __unicode__(self):
        return self.nombre


class Aspirante(models.Model):
    numero_documento = models.BigIntegerField(unique=True, verbose_name='número documento')
    nombre1 = models.CharField( max_length=255, verbose_name='primer nombre')
    nombre2 = models.CharField( max_length=255, blank=True, verbose_name='segundo nombre')
    apellido1 = models.CharField( max_length=255, verbose_name='primer apellido')
    apellido2 = models.CharField( max_length=255, blank=True, verbose_name='segundo apellido')

    sexo = models.CharField( choices=[('M','Hombre'), ('F', 'Mujer')], max_length=1, verbose_name='sexo')
    nacionalidad = models.CharField( max_length=255, blank=True, verbose_name='nacionalidad')
    fecha_nacimiento = models.DateField(verbose_name='fecha de nacimiento', help_text='Formato año-mes-día (ej: 1988-04-30)')
    municipio_nacimiento = models.ForeignKey(Municipio, null=True, blank=True, verbose_name='municipio de nacimiento', related_name='municipio_nacimiento')

    direccion = models.CharField( max_length=100, verbose_name='dirección')
    municipio = models.ForeignKey(Municipio, verbose_name='municipio de residencia', null=True)
    telefono = models.BigIntegerField(null=True, blank=True, verbose_name=u'teléfono fijo')
    celular = models.BigIntegerField(null=True, blank=True, verbose_name=u'número de celular')
    email = models.EmailField()

    puntuacion_hv = models.FloatField(null=True, blank=True)
    aceptado = models.NullBooleanField()

    institucion_actual = models.CharField(max_length=100, null=True, verbose_name=u'Institución donde labora actualmente')
    municipio_institucion = models.ForeignKey(Municipio, null=True, verbose_name=u'Municipio de la institución donde labora', related_name='institucionaspirante')
    jornada = models.CharField(max_length=5, null=True, choices=[('M', 'Mañana'), ('T', 'Tarde'), ('MT', 'Mañana y tarde')], verbose_name='jornada de trabajo')

    modificado = models.DateTimeField(null=True, auto_now=True)

    puntuacion_final = models.IntegerField(null=True, blank=True)

    def save(self, *args, **kwargs):
        debeCrearDocumentosSoporte = self.id is None
        super(Aspirante,self).save(*args, **kwargs)

        if debeCrearDocumentosSoporte:
            DocumentosSoporte.objects.create(aspirante=self)

    def __unicode__(self):
        #return (u"%s %s %s %s"%(self.nombre1,self.nombre2 or '', self.apellido1, self.apellido2 or '')).strip() or "-"
        return (u"%s %s %s"%(self.nombre1,self.nombre2 or '', self.apellido1)).strip() or "-"

    def nombreCompleto(self):
        return (u"%s %s %s %s"%(self.nombre1,self.nombre2 or '', self.apellido1,self.apellido2)).strip() or "-"

    def conocimientosEspecificos(self):
        return ConocimientosEspecificos.objects.filter(aspirante=self).latest('id')

    def calcular_puntaje(self):
        def maximo_puntaje(objetos):
            lista = list(objetos)
            if not lista : return 0
            return max(x.puntaje() for x in lista)

        MUNICIPIOS_ESPECIALES = (1089, 1057, 462, 279)
        punt_municipio = 10 if self.municipio_institucion_id in MUNICIPIOS_ESPECIALES else 0

        punt_academica = maximo_puntaje(self.formacionacademica_set.all())
        punt_tic = maximo_puntaje(self.formaciontics_set.all())
        punt_conocimientos = self.conocimientosespecificos.puntaje()
        punt_idioma = maximo_puntaje(self.idioma_set.all())

        punt_formador_estudiantes = maximo_puntaje(self.experienciaformador_set.filter(tipo__startswith='E'))
        punt_formador_profesores = maximo_puntaje(self.experienciaformador_set.filter(tipo__startswith='P'))
        punt_formador_formadores = maximo_puntaje(self.experienciaformador_set.filter(tipo__startswith='F'))

        return int(round(punt_municipio+punt_academica+punt_tic+punt_conocimientos+punt_idioma+
                punt_formador_estudiantes+punt_formador_profesores+punt_formador_formadores))

    def inscripcion_finalizada(self):
        return self.puntuacion_hv!=None

    def numero_inscripcion(self):
        mihash = (self.numero_documento*44383)%1000000007
        clave = "%d-%d"%(self.id, mihash)
        return clave



class FormacionAcademica(models.Model):
    NIVELES = (
        (10, 'Técnica'),
        (20, 'Tecnológica'),
        (30, 'Profesional'),
        (40, 'Especialización'),
        (50, 'Maestría'),
        (60, 'Doctorado')
    )
    aspirante = models.ForeignKey(Aspirante)

    nivel = models.IntegerField(choices=NIVELES, verbose_name='Nivel')
    titulo = models.CharField(max_length=255, verbose_name='título obtenido')
    fecha_inicio = models.DateField(verbose_name=u'fecha de inicio', help_text='Formato año-mes-día (ej: 1988-04-30)')
    fecha_terminacion = models.DateField(verbose_name='fecha de finalización')
    institucion = models.CharField(max_length=255, verbose_name=u'institución formadora')
    relacionado_pedagogia = models.BooleanField(verbose_name=u'este estudio está relacionado con la pedagogía')
    relacionado_tics = models.BooleanField(verbose_name=u'este estudio está relacionado con las TICs')

    def __unicode__(self):
        return self.titulo

    def puntaje(self):
        if self.nivel==60 and self.relacionado_tics : return 30 # doctorado areas afines a TIC
        if self.nivel==60 : return 28 # doctorado
        if self.nivel==50 and self.relacionado_tics : return 26 # maestria areas afines a TIC
        if self.nivel==50 : return 24 # maestria
        if self.nivel==40 and self.relacionado_tics : return 20 # especialicacion TIC
        if self.nivel==40 : return 15
        if self.nivel==30 and self.relacionado_pedagogia : return 10 # licenciatura en educacion o areas afines
        return 0


class FormacionTics(models.Model):
    DURACION_CURSO = (
        (4, 'Curso TIC mínimo 40 horas'),
        (6, 'Cursos TIC  hasta 90 horas'),
        (8, 'Cursos TIC hasta 140 horas certificados o en proceso de certificación'),
        (10, 'Cursos TIC mas 140 horas')
    )
    aspirante = models.ForeignKey(Aspirante)
    duracion = models.IntegerField(choices=DURACION_CURSO, verbose_name=u'duración del curso')
    titulo = models.CharField(max_length=255, verbose_name='título obtenido')
    fecha_inicio = models.DateField(verbose_name=u'fecha de inicio', help_text='Formato año-mes-día (ej: 1988-04-30)')
    fecha_terminacion = models.DateField(verbose_name='fecha de finalización', help_text='Formato año-mes-día (ej: 1988-04-30)')
    institucion = models.CharField(max_length=255, verbose_name=u'institución formadora')

    def __unicode__(self):
        return self.titulo

    def puntaje(self):
        return self.duracion


class ConocimientosEspecificos(models.Model):
    HABILIDAD_CONOCIMIENTO = (
        (0, 'Ninguno'),
        (1, 'Regular'),
        (2, 'Bueno'),
        (3, 'Muy bueno'),
    )
    aspirante = models.OneToOneField(Aspirante)
    conocimiento1 = models.IntegerField(choices=HABILIDAD_CONOCIMIENTO, verbose_name='Conocimiento y manejo de herramientas ofimáticas')
    conocimiento2 = models.IntegerField(choices=HABILIDAD_CONOCIMIENTO, verbose_name='Conocimiento y manejo de herramientas  Web 2')
    conocimiento3 = models.IntegerField(choices=HABILIDAD_CONOCIMIENTO, verbose_name='Conocimiento herramientas de edición multimedia')
    conocimiento4 = models.IntegerField(choices=HABILIDAD_CONOCIMIENTO, verbose_name='Experiencia en desarrollo de contenidos educativos digitales')
    conocimiento5 = models.IntegerField(choices=HABILIDAD_CONOCIMIENTO, verbose_name='Experiencia en desarrollo de libros de texto digital')
    conocimiento6 = models.IntegerField(choices=HABILIDAD_CONOCIMIENTO, verbose_name='Experiencia en procesos de e-learning')
    conocimiento7 = models.IntegerField(choices=HABILIDAD_CONOCIMIENTO, verbose_name='Experiencia en gestión de proyectos educativos TIC')
    conocimiento8 = models.IntegerField(choices=HABILIDAD_CONOCIMIENTO, verbose_name='Experiencia en desarrollo de elementos de evaluación de competencias.')

    def puntaje(self):
        total = 0
        for i in xrange(1,9):
            p = getattr(self, "conocimiento%d"%i)
            total += [0.0, 0.7, 1.3, 2.5][p]
        return total


class Idioma(models.Model):
    IDIOMAS = (
        ('ING', 'Inglés'),
        ('FRA', 'Francés'),
        ('ITA', 'Italiano'),
        ('ALE', 'Alemán'),
        ('POR', 'Portugués'),
        ('JAP', 'Japonés'),
    )
    HABILIDAD_IDIOMA = (
        (0, 'Nulo'),
        (1, 'Regular'),
        (2, 'Bueno'),
        (3, 'Muy bueno'),
    )

    aspirante = models.ForeignKey(Aspirante)
    idioma = models.CharField(max_length=3, choices = IDIOMAS, verbose_name=u'idioma extranjero')
    habla   = models.IntegerField(choices=HABILIDAD_IDIOMA, verbose_name='habilidad hablando')
    lee     = models.IntegerField(choices=HABILIDAD_IDIOMA, verbose_name='habilidad leyendo')
    escribe = models.IntegerField(choices=HABILIDAD_IDIOMA, verbose_name='habilidad escribiendo')

    def puntaje(self):
        punt_lee     = [0.0, 0.8, 1.5, 3][self.lee]

convocat2/templates/dashboard/multireporte_maestro_estudiante.html
<div class="row">
    <div class="col-md-12">
        <div class="panel panel-inverse" id="inscritos">
            <div class="panel-heading">
                <div class="panel-heading-btn">
                    <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-danger" data-click="panel-collapse"><i class="fa fa-minus"></i></a>
                </div>
                <h4 class="panel-title">Maestros Estudiantes Inscritos</h4>
            </div>
            <div class="panel-body">
                <div class="row">
                    <h6>Por favor haga clic en la columna que desea ocultar o mostrar</h6>
                    <a class="toggle-vis" data-column="0">#</a> |
                    <a class="toggle-vis" data-column="1">Nombres y Apellidos</a> |
                    <a class="toggle-vis" data-column="2">Cédula</a> |
                    <a class="toggle-vis" data-column="3">Institución Educativa</a> |
                    <a class="toggle-vis" data-column="4">Jornada</a> |
                    <a class="toggle-vis" data-column="5">Genero</a> |
                    <a class="toggle-vis" data-column="6">Email</a> |
                    <a class="toggle-vis" data-column="7">Email institucional</a> |
                    <a class="toggle-vis" data-column="8">Municipio de residencia</a> |
                    <a class="toggle-vis" data-column="9">Dirección</a> |
                    <a class="toggle-vis" data-column="10">Teléfono fijo</a> |
                    <a class="toggle-vis" data-column="11">Número de celular</a> |
                    <a class="toggle-vis" data-column="12">Último nivel educativo aprobado</a> |
                    <a class="toggle-vis" data-column="13">Secretaria educacion</a> |
                    <a class="toggle-vis" data-column="14">Sede</a> |
                    <a class="toggle-vis" data-column="15">Cargo</a> |
                    <a class="toggle-vis" data-column="16">Zona</a> |
                    <a class="toggle-vis" data-column="17">Decreto profesional docente</a> |
                    <a class="toggle-vis" data-column="18">Grados</a> |
                    <a class="toggle-vis" data-column="19">Poblacion étnica que atiende</a> |
                    <a class="toggle-vis" data-column="20">Tipo de nombramiento</a> |
                    <a class="toggle-vis" data-column="21">Tipo etnoeducador</a> |
                    <a class="toggle-vis" data-column="22">Asignaturas</a>
                </div><br/>
                <div class="table-responsive" style="overflow-y:auto; overflow-x:auto;">
                    <table id="tabla-super-poderosa" class="table table-striped table-bordered" width="100%">
                        <thead>
                            <tr role="row">
                                <th>#</th>
                                <th>Nombres y Apellidos</th>
                                <th>Cédula</th>
                                <th>Institución Educativa</th>
                                <th>Jornada</th>
                                <th>Genero</th>
                                <th>Email</th>
                                <th>Email institucional</th>
                                <th>Municipio de residencia</th>
                                <th>Dirección</th>
                                <th>Teléfono fijo</th>
                                <th>Número de celular</th>
                                <th>Último nivel educativo aprobado</th>
                                <th>Secretaria educacion</th>
                                <th>Sede</th>
                                <th>Cargo</th>
                                <th>Zona</th>
                                <th>Decreto profesional docente</th>
                                <th>Grados</th>
                                <th>Poblacion étnica que atiende</th>
                                <th>Tipo de nombramiento</th>
                                <th>Tipo etnoeducador</th>
                                <th>Asignaturas</th>
                            </tr>
                        </thead>
                        <tfoot>
                            <tr role="row">
                                <th>#</th>
                                <th>Nombres y Apellidos</th>
                                <th>Cédula</th>
                                <th>Institución Educativa</th>
                                <th>Jornada</th>
                                <th>Genero</th>
                                <th>Email</th>
                                <th>Email institucional</th>
                                <th>Municipio de residencia</th>
                                <th>Dirección</th>
                                <th>Teléfono fijo</th>
                                <th>Número de celular</th>
                                <th>Último nivel educativo aprobado</th>
                                <th>Secretaria educacion</th>
                                <th>Sede</th>
                                <th>Cargo</th>
                                <th>Zona</th>
                                <th>Decreto profesional docente</th>
                                <th>Grados</th>
                                <th>Poblacion étnica que atiende</th>
                                <th>Tipo de nombramiento</th>
                                <th>Tipo etnoeducador</th>
                                <th>Asignaturas</th>
                            </tr>
                        </tfoot>
                        <tbody>
                            {% for estudiante in estudiantesMulti %}
                                <tr class="odd gradeX" role="row">
                                    <td>{{forloop.counter}}</td>
                                    <td>{{estudiante}}</td>
                                    <td>{{estudiante.numero_documento}}</td>
                                    {% with infoLaboral=estudiante.infoLaboral %}
                                        <td>{{infoLaboral.get_sede_display}}</td>
                                        <td>{{infoLaboral.get_jornada_display}}</td>
                                        <td>{{estudiante.get_sexo_display}}</td>
                                        <td>{{estudiante.email}}</td>
                                        <td>{{estudiante.email_institucional}}</td>
                                        <td>{{estudiante.municipio}}</td>
                                        <td>{{estudiante.direccion}}</td>
                                        <td>{{estudiante.telefono}}</td>
                                        <td>{{estudiante.celular}}</td>
                                        <td>{{estudiante.get_nivel_educativo_display}}</td>
                                        <td>{{infoLaboral.secretaria_educacion}}</td>
                                        <td>{{infoLaboral.get_sede_display}}</td>
                                        <td>{{infoLaboral.get_cargo_display}}</td>
                                        <td>{{infoLaboral.get_zona_display}}</td>
                                        <td>{{infoLaboral.get_decreto_docente_display}}</td>
                                        <td>{% for grado in infoLaboral.grados.all %} {{ grado }} {% endfor %}</td>
                                        <td>{{infoLaboral.poblacion_etnica}}</td>
                                        <td>{{infoLaboral.get_nombramiento_display}}</td>
                                        <td>{{infoLaboral.get_tipo_etnoeducador_display}}</td>
                                        <td>{% for asignatura in infoLaboral.asignaturas.all %}
                                                {{ asignatura }}
                                            {% endfor %}
                                        </td>
                                    {% endwith %}
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

convocat2/templates/dashboard/multireporte_resultado_convocatoria.html
<div class="row">
    <div class="col-md-12">
        <div class="panel panel-inverse" id="inscritos">
            <div class="panel-heading">
                <div class="panel-heading-btn">
                    <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-danger" data-click="panel-collapse"><i class="fa fa-minus"></i></a>
                </div>
                <h4 class="panel-title">Maestros Aspirantes Inscritos</h4>
            </div>
            <div class="panel-body">
                <div class="row">
                    <h6>Por favor haga clic en la columna que desea ocultar o mostrar</h6>
                    <a class="toggle-vis" data-column="0">#</a> |
                    <a class="toggle-vis" data-column="1">Nombres y Apellidos</a> |
                    <a class="toggle-vis" data-column="2">Cédula</a> |
                    <a class="toggle-vis" data-column="3">Genero</a> |
                    <a class="toggle-vis" data-column="4">Nacionalidad</a> |
                    <a class="toggle-vis" data-column="5">Fecha de Nacimiento</a> |
                    <a class="toggle-vis" data-column="6">Municipio de Nacimiento</a> |
                    <a class="toggle-vis" data-column="7">Dirección</a> |
                    <a class="toggle-vis" data-column="8">Municipio</a> |
                    <a class="toggle-vis" data-column="9">Teléfono</a> |
                    <a class="toggle-vis" data-column="10">Celular</a> |
                    <a class="toggle-vis" data-column="11">Email</a> |
                    <a class="toggle-vis" data-column="12">Aceptado</a> |
                    <a class="toggle-vis" data-column="13">Institucion Actual</a> |
                    <a class="toggle-vis" data-column="14">Municipio Institución</a> |
                    <a class="toggle-vis" data-column="15">Jornada</a> |
                    <a class="toggle-vis" data-column="16">Conocimiento y manejo de herramientas ofimáticas</a> |
                    <a class="toggle-vis" data-column="17">Conocimiento y manejo de herramientas  Web 2</a> |
                    <a class="toggle-vis" data-column="18">Conocimiento herramientas de edición multimedia</a> |
                    <a class="toggle-vis" data-column="19">Experiencia en desarrollo de contenidos educativos digitales</a> |
                    <a class="toggle-vis" data-column="20">Experiencia en desarrollo de libros de texto digital</a> |
                    <a class="toggle-vis" data-column="21">Experiencia en procesos de e-learning</a> |
                    <a class="toggle-vis" data-column="22">Experiencia en gestión de proyectos educativos TIC</a> |
                    <a class="toggle-vis" data-column="23">Experiencia en desarrollo de elementos de evaluación de competencias</a>
                </div><br/>
                <div class="table-responsive" style="overflow-y:auto; overflow-x:auto;">
                    <table id="tabla-super-poderosa" class="table table-striped table-bordered" width="100%">
                        <thead>
                            <tr role="row">
                                <th>#</th>
                                <th>Nombres y Apellidos</th>
                                <th>Cédula</th>
                                <th>Genero</th>
                                <th>Nacionalidad</th>
                                <th>Fecha de Nacimiento</th>
                                <th>Municipio de Nacimiento</th>
                                <th>Dirección</th>
                                <th>Municipio</th>
                                <th>Teléfono</th>
                                <th>Celular</th>
                                <th>Email</th>
                                <th>Aceptado</th>
                                <th>Institucion Actual</th>
                                <th>Municipio Institución</th>
                                <th>Jornada</th>
                                <th>Conocimiento y manejo de herramientas ofimáticas</th>
                                <th>Conocimiento y manejo de herramientas  Web 2</th>
                                <th>Conocimiento herramientas de edición multimedia</th>
                                <th>Experiencia en desarrollo de contenidos educativos digitales</th>
                                <th>Experiencia en desarrollo de libros de texto digital</th>
                                <th>Experiencia en procesos de e-learning</th>
                                <th>Experiencia en gestión de proyectos educativos TIC</th>
                                <th>Experiencia en desarrollo de elementos de evaluación de competencias</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for aspirante in aspirantesMulti %}
                                <tr class="odd gradeX" role="row">
                                    <td>{{forloop.counter}}</td>
                                    <td>{{aspirante}}</td>
                                    <td>{{aspirante.numero_documento}}</td>
                                    <td>{{aspirante.get_sexo_display}}</td>
                                    <td>{{aspirante.nacionalidad}}</td>
                                    <td>{{aspirante.fecha_nacimiento}}</td>
                                    <td>{{aspirante.municipio_nacimiento}}</td>
                                    <td>{{aspirante.direccion}}</td>
                                    <td>{{aspirante.municipio}}</td>
                                    <td>{{aspirante.telefono}}</td>
                                    <td>{{aspirante.celular}}</td>
                                    <td>{{aspirante.email}}</td>
                                    <td>{% if aspirante.puntuacion_final == 100 %}
                                            SI
                                        {% else %}
                                            NO
                                        {% endif %}
                                    </td>
                                    <td>{{aspirante.institucion_actual}}</td>
                                    <td>{{aspirante.municipio_institucion}}</td>
                                    <td>{{aspirante.get_jornada_display}}</td>
                                    {% with conocimientosEspecificos=aspirante.conocimientosEspecificos %}
                                        <td>{{conocimientosEspecificos.get_conocimiento1_display}}</td>
                                        <td>{{conocimientosEspecificos.get_conocimiento2_display}}</td>
                                        <td>{{conocimientosEspecificos.get_conocimiento3_display}}</td>
                                        <td>{{conocimientosEspecificos.get_conocimiento4_display}}</td>
                                        <td>{{conocimientosEspecificos.get_conocimiento5_display}}</td>
                                        <td>{{conocimientosEspecificos.get_conocimiento6_display}}</td>
                                        <td>{{conocimientosEspecificos.get_conocimiento7_display}}</td>
                                        <td>{{conocimientosEspecificos.get_conocimiento8_display}}</td>
                                    {% endwith %}
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>