bilinguismo/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic.base import TemplateView
from django.contrib import admin
from django.conf import settings

urlpatterns = patterns('bilinguismo.views',
	url(r'bilinguismo/inscripcion$',      'inicioB', name="bilinguismo_inicio"),
    url(r'bilinguismo/datos-personales$',      'inscripcionB', name="bilinguismo_inscripcionB"),
    url(r'bilinguismo/datos-profesionales$',      'datosLaboralesB', name="bilinguismo_datosLaboralesB"),
    url(r'bilinguismo/formacion-academica$',      'formacionAcademicaB', name="bilinguismo_formacionAcademicaB"),
    url(r'bilinguismo/certificacion-bilinguismo$',      'certificacionB', name="bilinguismo_certificacionB"),
    url(r'bilinguismo/finalizar-bilinguismo/(\d+)$',      'finalizarB', name="bilinguismo_finalizarB"),

    # Eliminar Formacion Academica Bilinguismo
    url(r'bilinguismo/eliminarFormacionAcademicaB/(\d+)$',      'eliminarFormacionAcademicaB', name="eliminarFormacionAcademicaB"),
	# Eliminar Certificacion Bilinguismo
	url(r'bilinguismo/eliminarCertificacionB/(\d+)$',      'eliminarCertificacionB', name="eliminarCertificacionB"),
    #Resultados de Bilinguismo
    url(r'bilinguismo/reporte$',      'reporte', name="reporteBilinguismo"),
    url(r'bilinguismo/reporte/(\d+)$',      'reporte', name="reporteBilinguismo"),
    #url(r'impresion/(\d+)$',      'impresion', name="impresionBilinguismo"),
)

tita/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic.base import TemplateView
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

admin.autodiscover()


urlpatterns = static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) # solo en servidor de desarrollo


urlpatterns += patterns('',
    url(r'^select2/', include('django_select2.urls')),

    url(r'^logged_user$', 'campus.views.logged_user', name="logged_user"),

    url(r'^login/$', 'django.contrib.auth.views.login', {'template_name':'login.html'}, name='login'),
    url(r'^logout/$', 'django.contrib.auth.views.logout', {'next_page':'home'}, name='logout'),
    url(r'^cambiar-pass/$', 'django.contrib.auth.views.password_change', {'template_name':'cambiar-pass.html', 'post_change_redirect':'home'}, name='cambiar_pass'),

    url(r'^admin/', include(admin.site.urls)),

    #url(r'^$', TemplateView.as_view(template_name='info/index.html'), name='home'),
    url(r'^$', TemplateView.as_view(template_name='index.html'), name='home'),
    url(r'^antecedentes/$', TemplateView.as_view(template_name='info/antecedentes.html'), name="info_antecedentes"),
    url(r'^infogeneral/$', TemplateView.as_view(template_name='info/infogeneral.html'), name="info_general"),
    url(r'^calendario/$', TemplateView.as_view(template_name='info/calendario.html'), name="info_calendario"),
    url(r'^requisitos/$',TemplateView.as_view(template_name='info/requisitos.html'), name="info_requisitos"),
    url(r'^registrarse/$',TemplateView.as_view(template_name='info/registrarse.html'), name="info_registrarse"),
    url(r'^contactenos/$',TemplateView.as_view(template_name='info/contactenos.html'), name="info_contactenos"),
    #url(r'^tablero_control/$',TemplateView.as_view(template_name='dashboard/tablero_control.html'), name="tablero_control"),


    url('', include('convocat.urls')),
    url('', include('convocat2.urls')),
    url('', include('estudiante.urls')),
    url(r'^encuestas/', include('survey.urls')),
    url(r'^campus/', include('campus.urls')),
    url('', include('cronograma.urls')),
    url('', include('malla.urls')),
    url('', include('bilinguismo.urls')),
)

bilinguismo/models.py
#encoding: utf-8
from django.db import models
from estudiante.models import JORNADAS, Grado, Asignatura
from convocat.models import Municipio

class Bilinguismo(models.Model):

    NIVEL_EDUCATIVO = (
        (1, 'Sin título'),
        (2, 'Bachiller académico con profundización en pedagogía'),
        (3, 'Técnico o tecnólogo en educación'),
        (4, 'Técnico o tecnólogo en otras áreas'),
        (5, 'Profesional o licenciado en educación'),
        (6, 'Profesional en otras áreas, no licenciado'),
        (7, 'Postgrado en educación'),
        (8, 'Postgrado en otras áreas')
    )

    numero_documento = models.BigIntegerField(unique=True, verbose_name='número de documento de identidad *')
    nombre1 = models.CharField( max_length=255, verbose_name='primer nombre *')
    nombre2 = models.CharField( max_length=255, blank=True, verbose_name='segundo nombre')
    apellido1 = models.CharField( max_length=255, verbose_name='primer apellido *')
    apellido2 = models.CharField( max_length=255, blank=True, verbose_name='segundo apellido')
    sexo = models.CharField( choices=[('M','Hombre'), ('F', 'Mujer')], max_length=1, verbose_name='genero *')
    email = models.EmailField(verbose_name="email personal *")
    email_institucional = models.EmailField(blank=True, null=True)
    municipio = models.ForeignKey(Municipio, verbose_name='municipio de residencia', null=True)
    telefono = models.BigIntegerField(null=True, blank=True, verbose_name=u'teléfono fijo')
    celular = models.BigIntegerField(null=True, blank=True, verbose_name=u'número de celular')
    direccion = models.CharField(verbose_name="dirección *", max_length=100)
    nivel_educativo = models.IntegerField(choices=NIVEL_EDUCATIVO, verbose_name="último nivel educativo aprobado *")
    finalizada = models.BooleanField(default=False)
    cohorte = models.IntegerField(default=1)

    def __unicode__(self):
        return (u"%s %s %s %s"%(self.nombre1,self.nombre2 or '', self.apellido1, self.apellido2 or '')).strip() or "-"

    def numero_inscripcion(self):
        mihash = (self.numero_documento*44385)%1000000007
        clave = "%d-%d"%(self.id, mihash)
        return clave

    def inscripcion_finalizada(self):
    	return self.finalizada

class InfoLaboralBilinguismo(models.Model):
    ETNOEDUCADOR = (
        (1, 'No se desempeña como etnoeducador'),
        (2, 'Raizal'),
        (3, 'Afrocolombiano'),
        (4, 'Indígena')
    )

    INSTITUCIONES = (
    	(1, "IETI comuna 17"),
    	(2, "INEM Jorge Isaacs"),
    	(3, "Liceo Departamental"),
    	(4, "Normal Farallones de Cali"),
    	(5, "Celmira Bueno de Orejuela"),

        # Cohorte 2

        ('INEM JORGE ISAACS',
            ((6, 'Principal INEM JORGE ISAACS'),
            (7,  'Satelite CECILIA MUÑOZ RICAURTE'),
            (8,  'Satelite LAS AMERICAS'),
            (9,  'Satelite CAMILO TORRES'),
            (10,  'Satelite CENTRO EDUCATIVO DEL NORTE'),
            (11,  'Satelite FRAY DOMINGO DE LAS CASAS'),
            (12,  'Satelite PABLO EMILIO'))),
        ('ANTONIO JOSE CAMACHO',
            ((13, 'Principal ANTONIO JOSE CAMACHO'),
            (14, 'Satelite REPUBLICA DEL PERU'),
            (15, 'Satelite MARCO FIDEL SUAREZ'),
            (16, 'Satelite OLGA LUCIA LLOREDA'))),
        ('NORMAL. SUPERIOR SANTIAGO DE CALI',
            ((17, 'Principal NORMAL. SUPERIOR SANTIAGO DE CALI'),
            (18,  'Satelite JOAQUIN DE CAYZEDO Y CUERO'))),
        ('GOLONDRINAS PRINCIPAL',
            ((19, 'Principal GOLONDRINAS PRINCIPAL'),
            (20,  'Satelite ANTONIO BARBERENA'))),
        ('CARLOS HOLGUIN MALLARINO',
            ((21, 'Principal CARLOS HOLGUIN MALLARINO'),
            (22,  'Satelite NIÑO JESUS DE ATOCHA'),
            (23,  'Satelite MIGUEL DE POMBO'))),
        ('MANUEL MARIA MALLARINO',
            ((24, 'Principal MANUEL MARIA MALLARINO'),
            (25, 'Satelite LAURA VICUÑA'),
            (26, 'Satelite LOS PINOS'),
            (27, 'Satelite CARLOS HOLGUIN SARDI'))),
        ('EL DIAMANTE',
            ((28, 'Principal EL DIAMANTE'),
            (29, 'Satelite JUAN PABLO II'))),
        ('EUSTAQUIO PALACIOS',
            ((30, 'Principal EUSTAQUIO PALACIOS'),
            (31, 'Satelite    LUIS LOPEZ MESA'),
            (32, 'Satelite    CELANESE'),
            (33, 'Satelite    MANUEL MARIA BUENAVENTURA'),
            (34, 'Satelite    MARISCAL JORGE ROBLEDO'),
            (35, 'Satelite    MIGUEL ANTONIO CARO'),
            (36, 'Satelite    GENERAL ANZOATEGUI'),
            (37, 'Satelite    TULIO ENRIQUE TASCON'),
            (38, 'Satelite    SANTIAGO RENGIFO'),
            (39, 'Satelite    SOFIA CAMARGO'))),
        ('JOSE MARIA CARBONELL',
            ((40, 'Principal JOSE MARIA CARBONELL'),
            (41, 'Satelite HONORIO VILLEGAS'))),
        ('MARICE SINISTERRA',
            ((42, 'Principal MARICE SINISTERRA'),
            (43, 'Satelite FENALCO ASTURIAS'))),
            (44, 'Principal IE BOYACA'),
            (45, 'Principal YUMBO-IE MAYOR DE YUMBO - SEDE PRINCIPAL'),
            (46, 'Principal YUMBO-IE JOSÉ MARÍA CÓRDOBA - SEDE PRINCIPAL'),
            (47, 'Principal YUMBO-IE TITAN - SEDE PRINCIPAL'),
            (48, 'Principal YUMBO-IE CEAT GENERAL PIERO MARIOTTI - SEDE JOHN F. KENNEDY'),
            (49, 'Principal YUMBO-IE MANUEL MARÍA SÁNCHEZ - SEDE PRINCIPAL'),
            (50, 'Principal YUMBO-IE ROSA ZÁRATE DE PEÑA - SEDE PRINCIPAL'),
            (51, 'Principal VIJES'),
            (52, 'Otra IE Oficial'),
    )

    GRADO_ESCALAFON = (
        ('D.L 1278 de 2002',
            ((15, '1A'),
            (16,  '1B'),
            (17,  '1C'),
            (18,  '1D'),
            (19,  '2A'),
            (20,  '2B'),
            (21,  '2C'),
            (22,  '2D'),
            (23,  '3A'),
            (24,  '3B'),
            (25,  '3C'),
            (26,  '3D'))
            ),
        ('D.L 2277 de 1979',
            ((1, '01'),
            (2,  '02'),
            (3,  '03'),
            (4,  '04'),
            (5,  '05'),
            (6,  '06'),
            (7,  '07'),
            (8,  '08'),
            (9,  '09'),
            (10,  '10'),
            (11,  '11'),
            (12,  '12'),
            (13,  '13'),
            (14,  '14')))
    )

    HORARIOS = (
        (1, "Martes y jueves de 8 a 11 am"),
        (2, "Martes y jueves de 2 a 5 pm"),
        (3, "Miércoles de 1:00 pm a 7:00 pm (Nota: este horario se abre sólo si se reúne el cupo mínimo en su institución)"),
        (4, "Sábados de 7:00 am a 1:00 pm"),
        (5, "No definido")
    )


    persona = models.ForeignKey(Bilinguismo)

    institucion = models.IntegerField(choices=INSTITUCIONES, max_length=1, verbose_name="institución")
    otra_institucion = models.CharField(max_length=255, verbose_name="otra institución", blank=True, null=True)
    horario = models.IntegerField(choices=HORARIOS, verbose_name="Elija el horario que más le convenga para cursar el Diplomado", default=5) 
    cargo = models.IntegerField(choices=[(1, 'Docente'), (2, 'Rector'), (3, 'Coordinador'), (4, 'Otro')], verbose_name="cargo")
    zona = models.CharField( choices=[('R','Rural'), ('U', 'Urbana')], max_length=1, verbose_name='zona')
    jornada = models.CharField(choices=JORNADAS, max_length=1)
    grados = models.ManyToManyField(Grado)
    asignaturas = models.ManyToManyField(Asignatura)
    otra_asignatura = models.CharField(max_length=100, verbose_name="otra asignatura no registrada", null=True, blank=True)
    decreto_docente = models.IntegerField( choices=GRADO_ESCALAFON, max_length=1, verbose_name='decreto profesional docente')
    nombramiento = models.IntegerField(choices=[(1,'Propiedad'), (2, 'Período de Prueba'), (3, 'Provisional')], max_length=1, verbose_name='tipo de nombramiento')
    tipo_etnoeducador = models.IntegerField(choices=ETNOEDUCADOR)
    poblacion_etnica = models.CharField(max_length="100", verbose_name="poblacion étnica que atiende", null=True, blank=True)

class FormacionAcademicaBilinguismo(models.Model):
    NIVELES = (
        (10, 'Técnica'),
        (20, 'Tecnológica'),
        (30, 'Profesional'),
        (40, 'Especialización'),
        (50, 'Maestría'),
        (60, 'Doctorado')
    )
    persona = models.ForeignKey(Bilinguismo)

    nivel = models.IntegerField(choices=NIVELES, verbose_name='Nivel')
    titulo = models.CharField(max_length=255, verbose_name='título obtenido')
    institucion = models.CharField(max_length=255, verbose_name=u'institución formadora')
    relacionado_pedagogia = models.BooleanField(verbose_name=u'este estudio está relacionado con la pedagogía')
    relacionado_tic = models.BooleanField(verbose_name=u'este estudio está relacionado con las TIC')
    
    def __unicode__(self):
        return self.titulo

    '''def puntaje(self):
        if self.nivel==60 and self.relacionado_tics : return 30 # doctorado areas afines a TIC
        if self.nivel==60 : return 28 # doctorado
        if self.nivel==50 and self.relacionado_tics : return 26 # maestria areas afines a TIC
        if self.nivel==50 : return 24 # maestria
        if self.nivel==40 and self.relacionado_tics : return 20 # especialicacion TIC
        if self.nivel==40 : return 15
        if self.nivel==30 and self.relacionado_pedagogia : return 10 # licenciatura en educacion o areas afines
        return 0'''

class CertificacionBilinguismo(models.Model):
    DURACION_CURSO = (
        (40, 'Curso TIC mínimo 40 horas'),
        (90, 'Cursos TIC  hasta 90 horas'),
        (140, 'Cursos TIC hasta 140 horas certificados o en proceso de certificación'),
        (141, 'Cursos TIC mas 140 horas')
    )

    persona = models.ForeignKey(Bilinguismo)
    nombre = models.CharField(max_length=100, verbose_name="nombre del programa")
    duracion = models.IntegerField(choices=DURACION_CURSO)
    entidad = models.CharField(max_length=100, verbose_name="entidad certificadora")

    def __unicode__(self):
        return (u"%s"%self.nombre)

bilinguismo/forms.py
from django import forms
from bilinguismo.models import *
from convocat.forms import MyDateWidget, MunicipioChoice
from django_select2 import AutoModelSelect2Field, Select2MultipleWidget, Select2Widget

class BilinguismoForm(forms.ModelForm):

    municipio = MunicipioChoice(label = u"Municipio de residencia")
    class Meta:
        model = Bilinguismo
        exclude = ('inscripcion_finalizada', 'finalizada', 'cohorte')

class InfoLaboralBilinguismoForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(InfoLaboralBilinguismoForm, self).__init__(*args, **kwargs)
        self.fields['institucion'].choices = self.fields['institucion'].choices[6:]
        self.fields['horario'].choices = self.fields['horario'].choices[:-1]
    class Meta:
        model = InfoLaboralBilinguismo
        exclude = ('persona',)
        widgets = {
            'grados': Select2MultipleWidget(),
            'asignaturas': Select2MultipleWidget(),
        }

class FormacionAcademicaBilinguismoForm(forms.ModelForm):
    class Meta:
        model = FormacionAcademicaBilinguismo
        exclude = ('persona',)

class CertificacionBilinguismoForm(forms.ModelForm):
    class Meta:
        model = CertificacionBilinguismo
        exclude = ('persona',)

docente_estudiante/views/inscripcion.py
from django.shortcuts import redirect, render, render_to_response, get_object_or_404
from django.core import serializers
from convocat.models import * 
from django.db.models import Count
import json


def inscripcion(request):
    return render(request, 'inscripcion/inscripcion.html', {
    })

bilinguismo/templates/inscripcion/barra_estado.html
<div id="wizard">
<ol class="bwizard-steps clearfix" role="tablist">
    <li role="tab" {% if wizard_stage >= 1 %} aria-selected="true" class="active" {% endif %} style="z-index: 7;"><span class="label badge-inverse">1</span><a class="hidden-phone">
        Datos Personales
        </a>
    </li>
    <li role="tab"  {% if wizard_stage >= 2 %} aria-selected="true" class="active" {% endif %} style="z-index: 6;"><span class="label">2</span><a class="hidden-phone">
        Datos Profesionales 
        </a>
    </li>
    <li role="tab"  {% if wizard_stage >= 3 %} aria-selected="true" class="active" {% endif %} style="z-index: 5;"><span class="label">3</span><a class="hidden-phone">
        Formación Académica
        </a>
    </li>
    <li role="tab"  {% if wizard_stage >= 4 %} aria-selected="true" class="active" {% endif %} style="z-index: 4;"><span class="label">4</span><a class="hidden-phone">
        Certificación en Bilingüismo
        </a>
    </li>
</ol>
</div>
<br>

bilinguismo/templates/inscripcion/certificacionesB.html
{% extends "base.html" %}
{% load bootstrap3 %}

{% block titulo %} Formulario Bilingüismo {% endblock %}

{% block menu %}
    {% include "menus/publico.html" with opcion_menu=10 %}
{% endblock %}

{% block css %}
    <link href="{{STATIC_URL}}plugins/bootstrap-wizard/css/bwizard.min.css" rel="stylesheet" />
    {{form.media}} {# agrega los js y css necesarios para el bootstrap3 datetimepicker #}
{% endblock %}

{% block js %}
    {% if solo_lectura%}
    <script>
        $(function(){
            $("select").attr("disabled", "disabled");
            $("input").attr("readonly", "readonly");
        });
    </script>

    {% endif %}
{% endblock %}

{% block miga_pan %}
    <li><a href="{% url 'home' %}">Inicio</a></li>
    <li class="active">Formulario Bilingüismo</li>
{% endblock %}

{% block titulo_contenido %}Formulario Bilingüismo{% endblock %}

{% block previo_contenido_panel %}
    {% include "inscripcion/barra_estado.html" with wizard_stage=4 %}
{% endblock %}

{% block titulo_panel %}<i class="fa fa-lightbulb-o"></i> Inscripción{% endblock %}
{% block contenido_panel %}
    <div class="alert alert-info fade in m-b-15" align="center">
        Por favor guarde su número de registro: <b>{{clave}}</b>, es muy importante para futuros procesos.
    </div>
    <div class="row" style="margin-bottom:10px">
        <div class="col-sm-12">
            <table class="table table-hover">
                <thead>
                    <tr align="center">
                        <td><b>Nombre</b></td>
                        <td><b>Entidad</b></td>
                        <td></td>
                    </tr>
                    <tr></tr>
                </thead>
                <tbody>
                {% for certificacion in certificaciones %}
                    <tr align="center">
                        <td>{{certificacion}}</td>
                        <td>{{certificacion.entidad}}</td>
                        <td>
                            <a href="{% url 'eliminarCertificacionB' certificacion.id %}" onclick="return confirm('Seguro que desea eliminar esta entrada?')" class="text-danger">Eliminar</a>
                        </td>
                {% empty %}
                        <td colspan="5" align="center"><b>No hay certificaciones registradas</b></td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
        <div class="col-sm-12" align="center">
            {% if error %}
                <div class="alert alert-danger fade in m-b-15">
                    <center><strong>Error!</strong> {{error}}</center>
                </div>
            {% endif %}
            <form class="form-horizontal" method="post">{% csrf_token %}
                {% bootstrap_form form layout="horizontal" %}
                <br>
                <span class="alert alert-warning fade in m-b-15" align="center">
                    <b>Recuerde guardar los estudios digitados presionando "Guardar"</b>
                    <button class="btn btn-primary" type="submit">Guardar</button>
                </span>
            </form>
        </div>
    </div>
    
    <a href="{% url 'bilinguismo_formacionAcademicaB' %}" class="btn btn-lg btn-default pull-left"> <i class="fa fa-angle-left"></i> Anterior</a>
    <a id="siguiente" href="{% url 'bilinguismo_finalizarB' 1 %}" class="btn btn-lg btn-primary pull-right">Finalizar <small>(No podrá realizar cambios)</small><i class="fa fa-angle-right"></i></a>
    <a id="siguiente" href="{% url 'bilinguismo_finalizarB' 0 %}" class="btn btn-lg btn-danger pull-right" style="margin-right:10px">Completar Luego <i class="fa fa-angle-right"></i></a>
{% endblock %}

bilinguismo/templates/inscripcion/datosLaboralesB.html
{% extends "base.html" %}
{% load bootstrap3 %}

{% block titulo %} Formulario Bilingüismo {% endblock %}

{% block css %}
    <link href="{{STATIC_URL}}plugins/bootstrap-wizard/css/bwizard.min.css" rel="stylesheet" />
    {{form.media}} {# agrega los js y css necesarios para el bootstrap3 datetimepicker #}
{% endblock %}

{% block js %}
    {% if solo_lectura%}
    <script>
        $(function(){
            $("select").attr("disabled", "disabled");
            $("input").attr("readonly", "readonly");
        });
    </script>

    {% endif %}
    <script type="text/javascript">
        $( document ).ready(function() {
            function etnoeducador(){
                val = $("#id_tipo_etnoeducador").val();
                if(val < 2){
                    $('#id_poblacion_etnica').prop('readonly', true);
                    $('#id_poblacion_etnica').val('');
                }else{
                    $('#id_poblacion_etnica').prop('readonly', false);
                }
            }
            etnoeducador();

            $("#id_tipo_etnoeducador").on('change', function(){
                etnoeducador();
            })

            function institucion(){
                val = $("#id_institucion").val();
                if(val < 52){
                    $('#id_otra_institucion').prop('readonly', true);
                    $('#id_otra_institucion').val('');
                }else{
                    $('#id_otra_institucion').prop('readonly', false);
                }
            }
            institucion();
            
            $("#id_institucion").on('change', function(){
                institucion();
            })
        });
    </script>
{% endblock %}

{% block miga_pan %}
    <li><a href="{% url 'home' %}">Inicio</a></li>
    <li class="active">Formulario Bilingüismo</li>
{% endblock %}

{% block titulo_contenido %}Formulario Bilingüismo{% endblock %}

{% block previo_contenido_panel %}
    {% include "inscripcion/barra_estado.html" with wizard_stage=2 %}
{% endblock %}

{% block titulo_panel %}<i class="fa fa-lightbulb-o"></i> Inscripción{% endblock %}
{% block contenido_panel %}
    <div class="alert alert-info fade in m-b-15" align="center">
        Por favor guarde su número de registro: <b>{{clave}}</b>, es muy importante para futuros procesos.
    </div>
    <form class="form-horizontal" method="post">{% csrf_token %}
        {% bootstrap_form form layout="horizontal" %}

        <a href="{% url 'bilinguismo_inscripcionB' %}" class="btn btn-lg btn-default pull-left"> <i class="fa fa-angle-left"></i> Anterior</a>
        <button class="btn btn-lg btn-primary pull-right" type="submit">Siguiente <i class="fa fa-angle-right"></i></button>
        
    </form>
{% endblock %}

bilinguismo/templates/inscripcion/datosPersonalesB.html
{% extends "base.html" %}
{% load bootstrap3 %}

{% block titulo %} Formulario Bilingüismo {% endblock %}

{% block css %}
    <link href="{{STATIC_URL}}plugins/bootstrap-wizard/css/bwizard.min.css" rel="stylesheet" />
    {{form.media}} {# agrega los js y css necesarios para el bootstrap3 datetimepicker #}
{% endblock %}

{% block js %}
    {% if solo_lectura%}
    <script>
        $(function(){
            $("select").attr("disabled", "disabled");
            $("input").attr("readonly", "readonly");
        });
    </script>

    {% endif %}
{% endblock %}

{% block miga_pan %}
    <li><a href="{% url 'home' %}">Inicio</a></li>
    <li class="active">Formulario Bilingüismo</li>
{% endblock %}

{% block titulo_contenido %}Formulario de Bilingüismo{% endblock %}

{% block previo_contenido_panel %}
    {% include "inscripcion/barra_estado.html" with wizard_stage=1 %}
{% endblock %}

{% block titulo_panel %}<i class="fa fa-lightbulb-o"></i> Inscripción{% endblock %}
{% block contenido_panel %}
    <div class="alert alert-warning fade in m-b-15">
        <center><strong>Tenga en cuenta!</strong>
        Los campos marcados con * son obligatorios.</center>
    </div>
    <form class="form-horizontal" method="post">{% csrf_token %}
        {% bootstrap_form form layout="horizontal" %}

        <button class="btn btn-lg btn-primary pull-right" type="submit">Siguiente <i class="fa fa-angle-right"></i></button>
        
    </form>
{% endblock %}

bilinguismo/templates/inscripcion/finalizarB.html
{% extends "base.html" %}
{% load bootstrap3 %}

{% block titulo %} Formulario Bilingüismo {% endblock %}

{% block css %}
    <link href="{{STATIC_URL}}plugins/bootstrap-wizard/css/bwizard.min.css" rel="stylesheet" />
    {{form.media}} {# agrega los js y css necesarios para el bootstrap3 datetimepicker #}
{% endblock %}

{% block js %}
    {% if solo_lectura%}
    <script>
        $(function(){
            $("select").attr("disabled", "disabled");
            $("input").attr("readonly", "readonly");
        });
    </script>

    {% endif %}
{% endblock %}

{% block miga_pan %}
    <li><a href="{% url 'home' %}">Inicio</a></li>
    <li class="active">Formulario Bilingüismo</li>
{% endblock %}

{% block titulo_contenido %}Formulario de Bilingüismo{% endblock %}

{% block previo_contenido_panel %}
    {% include "inscripcion/barra_estado.html" with wizard_stage=4 %}
{% endblock %}

{% block titulo_panel %}<i class="fa fa-lightbulb-o"></i> Finalización{% endblock %}
{% block contenido_panel %}
    <center><h3>
    {% if tipo == '0' %}
        Recuerde posteriormente culminar la inscripción. Gracias por su interés.
    {% else %}
        Su inscripción ha sido exitosa.  Gracias por su interés.
    {% endif %}
    </h3></center>

    <center>
        <a href="{% url 'bilinguismo_inicio' %}">
            <button class="btn btn-primary">
                Volver al inicio
            </button>
        </a>
    </center>
{% endblock %}